### PR TITLE
Fix App crash when string values provided in labOrTheory section

### LINKED ISSUE #38: App crashes when unknown values are given in the lab or theory section

### PR DESCRIPTION
**Pull request by Abir-Tx**
Fixes #38

### CODE REVIEW

File: include/create.hpp [hunk 1]
```diff
@@ -28,6 +29,17 @@ int gotoLabOrTheory;
...
+      {
+          for (int i = 0; i < s.length(); i++)
+              if (isdigit(s[i]) == false)
+                  return false;
+      
+          return true;
+      }
+
+
+// The main driver Func
```
Comment (Abir-Tx) [inline include/create.hpp:42]: this is main function of this create.hpp file. This function creates folders and take all the necessary inputs

**Comment by Abir-Tx** [comment]
The bug is fixed successfully now
